version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
references:
  bundle: &bundle
    run:
      name: Run bundler
      command: bundle -v; bundle config set path 'vendor/bundle'; bundle install
  migrations: &migrations
    run:
      name: Run db migrations
      command: bundle exec rake db:migrate
  run_linter: &run_linter
    run:
      name: Run linter
      command: bundle exec rake standard
  run_tests: &run_tests
    run:
      name: Run test suite
      command: bundle exec rspec

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.1
    resource_class: small
    executor: ruby/default
    steps:
      - checkout
      - <<: *bundle
      - <<: *migrations
      - <<: *run_linter
      - <<: *run_tests
