name: derekgottlieb/linkdump
on:
  push:
    branches:
    - main
env:
  APP_ENV: test
  RACK_ENV: test
  RAILS_ENV: test
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.2.2
    steps:
    - uses: actions/checkout@v3.6.0
    - name: Run bundler
      run: bundle -v; bundle config set path 'vendor/bundle'; bundle install
    - name: Run db migrations
      run: bundle exec rake db:migrate
    - name: Run linter
      run: bundle exec rake standard
    - name: Run test suite
      run: bundle exec rspec
